### ISSUE TITLE
Investigate creating an image repository for each OS

### ISSUE THREAD

**Issue by ddebeau** [enthought/edm-containers#20]
It may be more user friendly to have a repository for each OS, instead of publishing all images to one repository. We should investigate best practices.

**Comment by ZachPope531** [comment]
It may be more user friendly to have one repo per image, but it also will be more expensive/wasteful. I'm not sure what plan we use, but Quay.io only gives us so many private repos: https://quay.io/plans/
If we wanted to make them public repos then it's all good, we can make as many as we want.

On whether we should have one repo, multiple tags or multiple repos, one tag: 
From what I can tell, the latter is the better option since barely anyone online is even talking about the former. The former doesn't really allow us to do versioning the standard way, since the `latest` tag may point to one of any images we uploaded. So if someone just called `docker pull quay.io/enthought/edm-containers` there'd be no guarantee they'd get the latest version of the image they wanted but instead the image that was pushed last.

**Comment by ddebeau** [comment]
Ticket for creating repositories on Quay and Dockerhub:
http://enthought.zendesk.com/agent/tickets/94684

**Comment by ddebeau** [comment]
Image repositories created.
